package cmd

import (
	"fmt"

	"andromeda.ottopay.id/pt-rtsm-ottopay/skeleton-svc/internal/generator"
	"github.com/charmbracelet/huh"
	"github.com/spf13/cobra"
)

var addCmd = &cobra.Command{
	Use:   "add",
	Short: "Add components to an existing project",
	Long: `Extend your project by adding infrastructure modules, feature routes, CRUD stacks, helpers, or host integrations.
This command must be run inside a project generated by skeleton-svc.`,
}

var addModuleCmd = &cobra.Command{
	Use:   "module [name]",
	Short: "Add an infrastructure module",
	Long: `Add a new infrastructure module to your project. 
For messaging brokers (NATS, Kafka, Asynq), you will be prompted to select a role (Consumer, Publisher, or Both).

Available Modules:
- Databases: mysql, postgresql
- Caching: redis, redis-cluster
- Messaging: nats, kafka, asynq
- Storage: minio

Example:
  skeleton-svc add module redis
  skeleton-svc add module nats`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		module := ""
		if len(args) > 0 {
			module = args[0]
		} else {
			if err := huh.NewSelect[string]().
				Title("Select Module").
				Options(huh.NewOptions("mysql", "postgresql", "redis", "redis-cluster", "kafka", "nats", "asynq", "minio")...).
				Value(&module).
				Run(); err != nil {
				return fmt.Errorf("add module cancelled: %w", err)
			}
		}

		// For messaging brokers, ask for role
		messagingBrokers := map[string]bool{"nats": true, "kafka": true, "asynq": true}
		if messagingBrokers[module] {
			role := "Consumer"
			if err := huh.NewSelect[string]().
				Title("Messaging Role").
				Description(fmt.Sprintf("How will this service use %s?", module)).
				Options(huh.NewOptions("Consumer", "Publisher", "Both")...).
				Value(&role).
				Run(); err != nil {
				return fmt.Errorf("add module cancelled: %w", err)
			}

			fmt.Printf("Adding module %s as %s...\n", module, role)
			// Always add base infra module
			if err := generator.AddModule(module); err != nil {
				return fmt.Errorf("failed to add module: %w", err)
			}
			// Add role-specific sub-modules
			if role == "Consumer" || role == "Both" {
				if err := generator.AddModule(module + "-consumer"); err != nil {
					return fmt.Errorf("failed to add consumer module: %w", err)
				}
			}
			if role == "Publisher" || role == "Both" {
				if err := generator.AddModule(module + "-publisher"); err != nil {
					return fmt.Errorf("failed to add publisher module: %w", err)
				}
			}
			fmt.Printf("✓ Module %s (%s) added successfully!\n", module, role)
			return nil
		}

		fmt.Printf("Adding module %s...\n", module)
		if err := generator.AddModule(module); err != nil {
			return fmt.Errorf("failed to add module: %w", err)
		}
		fmt.Printf("✓ Module %s added successfully!\n", module)
		return nil
	},
}

var addRouteCmd = &cobra.Command{
	Use:   "route <name>",
	Short: "Add a new feature route stack",
	Long: `Scaffold a basic Controller and Usecase stack for a single endpoint.
Useful for simple pages or non-entity actions like 'health' or 'login'.

Example:
  skeleton-svc add route healthcheck`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		fmt.Printf("Generating feature stack for %s...\n", name)
		if err := generator.AddFeature(name); err != nil {
			return fmt.Errorf("failed to generate feature: %w", err)
		}
		fmt.Printf("✓ Feature %s generated successfully!\n", name)
		return nil
	},
}

var addCrudCmd = &cobra.Command{
	Use:   "crud <name>",
	Short: "Add a full CRUD entity stack",
	Long: `Generate a complete CRUD stack for a business entity, including:
- Controller (Fiber handlers)
- Usecase (Business logic)
- Repository (Database interactions)
- Model (DTOs and Entities)
- Router registration

Example:
  skeleton-svc add crud product --db postgresql`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		dbType, _ := cmd.Flags().GetString("db")
		fmt.Printf("Generating CRUD for %s...\n", name)
		if err := generator.AddCRUD(name, dbType); err != nil {
			return fmt.Errorf("failed to generate CRUD: %w", err)
		}
		fmt.Printf("✓ CRUD feature %s generated successfully!\n", name)
		return nil
	},
}

var addHostCmd = &cobra.Command{
	Use:   "host <name>",
	Short: "Add an external API host integration",
	Long: `Scaffold a standardized client to interact with an external service.
It creates a dedicated host package with its own DTOs and HTTP client wrapper.

Example:
  skeleton-svc add host payment-gateway`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		fmt.Printf("Adding host integration for %s...\n", name)
		if err := generator.AddHost(name); err != nil {
			return fmt.Errorf("failed to add host: %w", err)
		}
		fmt.Printf("✓ Host %s added successfully!\n", name)
		return nil
	},
}

var addHelperCmd = &cobra.Command{
	Use:   "helper <name>",
	Short: "Add a new helper utility stub",
	Long: `Generate a new helper function stub in the helpers/ directory.

Example:
  skeleton-svc add helper password-hash`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		fmt.Printf("Generating helper %s...\n", name)
		if err := generator.AddHelper(name); err != nil {
			return fmt.Errorf("failed to generate helper: %w", err)
		}
		fmt.Printf("✓ Helper %s generated successfully!\n", name)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(addCmd)
	addCmd.AddCommand(addModuleCmd)
	addCmd.AddCommand(addRouteCmd)
	addCmd.AddCommand(addCrudCmd)
	addCmd.AddCommand(addHostCmd)
	addCmd.AddCommand(addHelperCmd)
	addCrudCmd.Flags().StringP("db", "d", "", "Database type (mysql, postgresql)")
}
